// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestAPI.Models;

namespace TestAPI.Migrations
{
    [DbContext(typeof(StatementDetailContext))]
    partial class StatementDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestAPI.Models.StatementDetail1", b =>
                {
                    b.Property<int>("StatementDetailId1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAdress")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KidBirthday1")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("KidName1")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KidPatronymic1")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KidSurname1")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerBirthday1")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OwnerINN")
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("OwnerName1")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerPatronymic1")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerSurname1")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasportNumber1")
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("PasportSet1")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("PasportType1")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("СertificateNumber1")
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("СertificateSet1")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("СertificateType1")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatementDetailId1");

                    b.ToTable("StatementDetails1");
                });

            modelBuilder.Entity("TestAPI.Models.StatementDetail2", b =>
                {
                    b.Property<int>("StatementDetailId2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KidBirthday2")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("KidName2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KidPatronymic2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KidSurname2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerBirthday2")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OwnerName2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerPatronymic2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerSnils")
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("OwnerSurname2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasportNumber2")
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("PasportSet2")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("PasportType2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("СertificateNumber2")
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("СertificateSet2")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("СertificateType2")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatementDetailId2");

                    b.ToTable("StatementDetails2");
                });
#pragma warning restore 612, 618
        }
    }
}
